cinemake/config/routes.rb
Rails.application.routes.draw do

  ###Application Routes ###
  get '/', to: 'application#welcome', as: 'welcome'
  get '/search', to: 'application#search', as: 'search'
  
  ###Session Routes
  get '/login', to: 'sessions#new', as: 'login'

  get '/signup', to: 'directors#new', as: 'signup'

  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout', as: 'logout'

  #Actors Test
  get '/test', to: 'actors#test', as: 'test'
  ###Crew Members###

  get '/crew_members/search', to: 'crew_members#index', as: 'crew_members_search'
  get '/crew_members/:id', to: 'crew_members#show', as: 'crew_member'
  get '/movies/:id/crew_members', to: 'crew_members#movie_index', as: 'movie_crew_members'
  
  post 'crew_members', to: 'crew_members#create', as: 'create_crew_members'


  ### Roles Routes ###
  get 'crew_members/:id/roles/new', to: 'roles#new', as: 'new_role'
  
  post 'roles/new', to: 'roles#create', as: 'roles'
  
  ###Directors Routes###
  
  get '/directors/edit', to: 'directors#edit', as: 'edit_director'
  get '/directors/:id', to: 'directors#show', as: 'director'
  get '/director/:id/friends', to: 'directors#friends', as: 'director_friends'
  get '/director/:id/friends/pending', to: 'directors#pending_friends', as: 'pending_friends'
  
  post '/directors', to: 'directors#create', as: 'directors'
  patch '/directors/:id', to: 'directors#update'
  delete '/directors/:id', to: 'directors#destroy'

  ###Projects Routes###

  get '/directors/:id/projects', to: 'projects#index', as: 'director_projects'
  get '/movies/:id/projects/new', to: 'projects#new', as: 'new_project'
  get '/projects/:id', to: 'projects#show', as: 'project'
  get '/movies/:id/projects', to: 'projects#movie_index', as: 'movie_projects'

  post '/projects', to: 'projects#create', as: 'projects'
  patch '/projects', to: 'projects#update'

  ###Movies###
  get '/movies', to: 'movies#index', as: 'movies'
  get '/directors/:id/movies', to: 'movies#director_index', as: 'director_movies'
  get '/movies/new', to: 'movies#new', as: 'new_movie'
  get '/movie/:id', to: 'movies#show', as: 'movie'

  post '/movies', to: 'movies#create'
  
  ###Project Crew Members###
  get '/projects/:id/crew_members/new', to: 'project_crew_members#new', as: 'new_project_crew_member'

  post '/projects/:id/crew_members', to: 'project_crew_members#create', as: 'project_crew_members'

  ###Friends###
  post '/friends', to: 'friends#create', as: 'friends'
  patch '/friends', to: 'friends#update'

  ###Posts###

  get '/directors/:id/posts', to: 'posts#director_index', as: 'director_posts'
  get '/posts/new', to: 'posts#new', as: 'new_post'
  get '/posts/:id', to: 'posts#show', as: 'post'

  post '/posts', to: 'posts#create', as: 'posts'


end

cinemake/app/models/director.rb
class Director < ApplicationRecord
    
    has_secure_password
    
    has_many :director_movies
    has_many :movies, through: :director_movies
    has_many :posts
    
    validates :name, presence: true
    validates :age, presence: true
    validate :age_is_over_13
    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :username, presence: true, uniqueness: true
    # confirmation: true
    
    def age_is_over_13
        if age.present? && age < 13
            errors.add(:age, "cannot be less than 13")
        end
    end

    def self.names
        self.all.map{|director|director.name}
    end
    
    def projects
        self.movies.map{|movie| movie.projects}.flatten
    end
    
    def most_recent_three_projects
        self.projects.sort_by{|project| project.created_at}.last(3).reverse
    end

    def friend_requests
        Friend.all.select{|friend| friend.friender == self || friend.friendee == self}.uniq
    end

    def friends
        self.friend_requests.select{|friend| friend.status == "accepted"}
    end

    def pending_friends
        self.friend_requests.select{|friend| friend.status == "pending"}
    end

    def inbound_pending_requests
        self.pending_friends.select{|friend| friend.friendee == self}
    end

    def director_friends
        self.friends.map{|friend| [friend.friender, friend.friendee]}.flatten.reject{|friend| friend == self}
    end

    def friend_names
        self.director_friends.map{|director|director.name}
    end

    def has_pending_friend_requests?
        self.pending_friends.find{|friend| friend.friendee == self}
    end

    def has_left_friend_request?(director)
        self.pending_friends.find{|friend| friend.friender == self && friend.friendee == director}
    end
end

cinemake/app/controllers/directors_controller.rb
class DirectorsController < ApplicationController

    before_action :valid?, except: [:new, :create]

    def new
        if session[:user]
            redirect_to director_path(user)
        else
            @director = Director.new
        end
    end

    def create
        @director = Director.new(director_params)
        if @director.valid?
            @director.save
            session[:user] = @director
            redirect_to director_path(@director)
        else
            render :new
        end
    end

    def show
        @director = Director.find(params[:id])
        @friend = Friend.new
    end

    def pending_friends
        @director = Director.find(params[:id])
    end
    
    private
        
    def director_params
        params.require(:director).permit(:name, :username, :password, :nationality, :email, :age, :image)
    end
end

cinemake/app/helpers/directors_helper.rb
module DirectorsHelper
end

cinemake/app/views/directors/new.html.erb
<body>
    <div id="welcome_logo" ><img id="big_logo" src="/cinemake.png"></div>
    <% if @director.errors.any? %>
    <ul>
        <% @director.errors.full_messages.each do |error| %>
            <li> <%= error %></li>
        <% end %>
    </ul>    
    <%end%>

<h5><%= form_with model: @director, url: directors_path, method: :post do |form| %>
            
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.label :age %>
    <%= form.number_field :age %><br><br>
    <%= form.label :nationality %>
    <%= form.country_select :nationality, ['United States'] %><br><br>
    <%= form.label :email%>
    <%= form.text_field :email%><br><br>
    <%= form.label :image, "Profile Image URL"%>
    <%= form.text_field :image%><br><br><br><br><br>
    <%= form.label :username %>
    <%= form.text_field :username %><br><br>
    <%= form.label :password %>
    <%= form.password_field :password %><br><br>
    <!-- <%= form.label :password_digest_confirmation, "Confirm Password" %> -->
    <!-- <%= form.password_field :password_confirmation %><br><br> -->
    <%= form.submit "Create Account" %>

<% end %> </h5>
   

cinemake/app/views/directors/pending_friends.html.erb
<h2>Pending Friend Requests</h2>
<hr class="hr2">
    <%if @director.inbound_pending_requests.empty? %>
        <p>You have no pending requests</p>
    <% else %>
        <div class="person_search"><% @director.inbound_pending_requests.each do |friend| %>
        <div class="card" style="width: 18rem;">
            <img src="<%=friend.friender.image%>" class="card-img-top" alt="...">
            <div class="card-body">
            <h5 class="card-title"><%= link_to "#{friend.friender.name}", director_path(friend.friender) %></h5>
            <p class="card-text"><%= form_with model: friend, url: friends_path, method: :patch, local: true do |f| %>
                <%= f.hidden_field :id, :value => friend.id %>
                <%= f.hidden_field :status, :value => 'accepted' %>
                <%= f.submit "Accept"%>
            <% end %></p>
    </div>
    </div>
        <% end %></div>
    <% end %>
        

cinemake/app/views/directors/show.html.erb
<% user = Director.find(session[:user]["id"]) %>
    <div class="flex-container">
        <img src=<%="#{@director.image}"%> class="profile_image" alt="Responsive image">
    </div>
<h2><%=@director.name%></h2><br>
    <hr class="hr2">
    <% if @director.id == user.id%>
        <% if user.has_pending_friend_requests? %>
        <h5>You have pending friend requests<br>
            <%= button_to "Click Here to View", pending_friends_path, method: :get %></h5><br>
        <% end %>
    <% end %>
    <div class="profile_options">
    |
    <%= link_to "Movies", director_movies_path(@director) %>
    |
    <%= link_to "Posts", director_posts_path(@director) %>
    |
    <%= link_to "Projects", director_projects_path(@director) %>
    |
    
    <% if @director.id != user.id %>
        <% if user.director_friends.include?(@director)%>
            <%= @director.email%>
            |<br><br>
        <% elsif user.has_left_friend_request?(@director) %>
            <p>Friend Request Pending</p>
            |
        <% else %>
            <%= form_with model: @friend, url: friends_path, local: true do |f| %>
                <%= f.hidden_field :friender_id, :value => user.id %>
                <%= f.hidden_field :friendee_id, :value => @director.id %>
                <%= f.hidden_field :status, :value => "pending" %>
                <%= f.submit "Send Friend Request"%>
                
            <% end %>|
        <% end %>
    <% end %>
</div>
<br>