cinemake/config/routes.rb
Rails.application.routes.draw do

  ###Application Routes ###
  get '/', to: 'application#welcome', as: 'welcome'
  get '/search', to: 'application#search', as: 'search'
  
  ###Session Routes
  get '/login', to: 'sessions#new', as: 'login'

  get '/signup', to: 'directors#new', as: 'signup'

  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout', as: 'logout'

  #Actors Test
  get '/test', to: 'actors#test', as: 'test'
  ###Crew Members###

  get '/crew_members/search', to: 'crew_members#index', as: 'crew_members_search'
  get '/crew_members/:id', to: 'crew_members#show', as: 'crew_member'
  get '/movies/:id/crew_members', to: 'crew_members#movie_index', as: 'movie_crew_members'
  
  post 'crew_members', to: 'crew_members#create', as: 'create_crew_members'


  ### Roles Routes ###
  get 'crew_members/:id/roles/new', to: 'roles#new', as: 'new_role'
  
  post 'roles/new', to: 'roles#create', as: 'roles'
  
  ###Directors Routes###
  
  get '/directors/edit', to: 'directors#edit', as: 'edit_director'
  get '/directors/:id', to: 'directors#show', as: 'director'
  get '/director/:id/friends', to: 'directors#friends', as: 'director_friends'
  get '/director/:id/friends/pending', to: 'directors#pending_friends', as: 'pending_friends'
  
  post '/directors', to: 'directors#create', as: 'directors'
  patch '/directors/:id', to: 'directors#update'
  delete '/directors/:id', to: 'directors#destroy'

  ###Projects Routes###

  get '/directors/:id/projects', to: 'projects#index', as: 'director_projects'
  get '/movies/:id/projects/new', to: 'projects#new', as: 'new_project'
  get '/projects/:id', to: 'projects#show', as: 'project'
  get '/movies/:id/projects', to: 'projects#movie_index', as: 'movie_projects'

  post '/projects', to: 'projects#create', as: 'projects'
  patch '/projects', to: 'projects#update'

  ###Movies###
  get '/movies', to: 'movies#index', as: 'movies'
  get '/directors/:id/movies', to: 'movies#director_index', as: 'director_movies'
  get '/movies/new', to: 'movies#new', as: 'new_movie'
  get '/movie/:id', to: 'movies#show', as: 'movie'

  post '/movies', to: 'movies#create'
  
  ###Project Crew Members###
  get '/projects/:id/crew_members/new', to: 'project_crew_members#new', as: 'new_project_crew_member'

  post '/projects/:id/crew_members', to: 'project_crew_members#create', as: 'project_crew_members'

  ###Friends###
  post '/friends', to: 'friends#create', as: 'friends'
  patch '/friends', to: 'friends#update'

  ###Posts###

  get '/directors/:id/posts', to: 'posts#director_index', as: 'director_posts'
  get '/posts/new', to: 'posts#new', as: 'new_post'
  get '/posts/:id', to: 'posts#show', as: 'post'

  post '/posts', to: 'posts#create', as: 'posts'


end

cinemake/app/controllers/movies_controller.rb
class MoviesController < ApplicationController

    def index
        @movies = Movie.all
    end

    def show
        @movie = Movie.find(params[:id])
    end
    
    def new
        @movie = Movie.new
    end

    def create
        @movie = Movie.new(movie_params)
        if @movie.valid?
            @movie.save
            DirectorMovie.create(:director_id => session[:user]["id"], :movie_id => @movie.id)
            redirect_to movie_path(@movie)
        else
            render :new
        end
    end

    def director_index
        @director = Director.find(params[:id])
    end

    private
    def movie_params
        params.require(:movie).permit(:name, :release_year, :synopsis, :production_company, :language_id)
    end
end

cinemake/app/helpers/movies_helper.rb
module MoviesHelper
end

cinemake/app/views/movies/director_index.html.erb
<title>New Director</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<% stylesheet_link_tag 'application', media: 'all', 'data-turbo-links-track-': 'reload' %>
<link rel = "stylesheets"
    type = "text/css"
    href = "../assets/stylesheets/application.css" />

<h1><%=@director.name%>'s Movies</h1>
       
<% if @director.id == session[:user]["id"] %>
    <h5><%= button_to "Make a Movie", new_movie_path, method: :get %></h5><br><br> 
<% end %>
   
<div class="flex-container">
    <% unless @director.movies.empty? %>
        <% @director.movies.each do |movie| %>
            
<div class="card" style="width: 18rem;">
<div class="card-body">
    <h5 class="card-title"><%="#{movie.name} (#{movie.release_year})"%></h5>
        <p class="card-text"><%=movie.short_synopsis%></p>
        <a href=<%= movie_path(movie) %> class="btn btn-primary"><%="#{movie.name} (#{movie.release_year})"%></a>
</div>
</div>
    <% end %>
</div>
    <% else %>
       This Director has no movies.
    <% end %> 

cinemake/app/views/movies/new.html.erb
<h1>Make Your Movie</h1>

<% if @movie.errors.any? %>
    <ul>
        <% @movie.errors.full_messages.each do |error| %>
        <li><%= error %></li>
        <% end %>
    </ul>
<% end %>
<h5>
<%= form_with model: @movie, url: movies_path, local: true, method: :post do |form| %>
    <%= form.label :name, "Movie Name:" %>
    <%= form.text_field :name, size: 35%><br><br>
    <%= form.label :release_year, "Planned Release Year: "%>
    <%= form.select :release_year, (Time.zone.now.year.to_i)..(Time.zone.now.year + 100).to_i %><br><br>
    <%= form.label :synopsis, "Synopsis: "%>
    <div><%= form.text_area :synopsis, cols: 50, rows: 10%></div><br>
    <%= form.label :production_company, "Production Company" %>
    <%= form.text_field :production_company %><br><br>
    <%= form.label :language_id %>
    <%= form.select :language_id, Language.all.map{|l| [l.name, l.id]} %><br><br>
    <%= form.submit "Create Movie" %>
<% end %>
</h5>
   

cinemake/app/views/movies/show.html.erb
<br><br>
<div class="post">
<h3><%= "#{@movie.name} (#{@movie.release_year})" %></h3>
<hr class="hr">
    <h3>Cast and Crew</h3>

    <h6>
    Directors:
    <% @movie.directors.each do |director|%>
        <%= director.name %> 
    <% end %> 
    </h6>
            
    <% unless @movie.writers.empty? %>
        <div>
            Writers:
            <% @movie.writers.each do |writer|%>
                <%= "#{writer.name} (#{writer.movie_role(@movie).name})" %>
            <% end %> 
        </div>
    <% end %>

    <h6>    
    <% unless @movie.stars.empty? %>
         <div>Stars: 
        <%= @movie.star_array.join(",  ") %></div>
    <% end %>
    </h6>
    <% link_to "Full Cast and Crew", movie_crew_members_path(@movie) %>
    <div>
    <% if @movie.director_ids.include?(session[:user]["id"]) %>
        <br>
        <%= button_to "Search for new Cast and Crew Members", crew_members_search_path, method: :get %>
        <br>
    <% end %>
    </div>
    <br>
    <hr class="hr3">
    
    <h4>Projects</h4>

    <% if @movie.projects.any? %>
        <% @movie.most_recent_three_projects.each do |project| %>
            <div><h4><%= link_to "#{project.name}", project_path(project) %></h4>
            <p>Status: <%= project.status %> Start: <%= project.start_date %> Finish: <%= project.end_date %></p>
            <hr class="hr3"></div>
        <% end %>
        <%= link_to "Show More", movie_projects_path(@movie)%>
    <% else %>
        <p>This movie has no projects.
            <% if @movie.director_ids.include?(session[:user]["id"]) %>
                Projects are a great way to keep track of the stuff you need to get done for your movie, from buying props to filming scenes.<br>
                <%= button_to "Add a New Project Now!", new_project_path(@movie), method: :get %>
            <% end %></p>
    <% end %></div>
</div>
</div>
   