cinemake/config/routes.rb
Rails.application.routes.draw do

  ###Application Routes ###
  get '/', to: 'application#welcome', as: 'welcome'
  get '/search', to: 'application#search', as: 'search'
  
  ###Session Routes
  get '/login', to: 'sessions#new', as: 'login'

  get '/signup', to: 'directors#new', as: 'signup'

  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout', as: 'logout'

  #Actors Test
  get '/test', to: 'actors#test', as: 'test'
  ###Crew Members###

  get '/crew_members/search', to: 'crew_members#index', as: 'crew_members_search'
  get '/crew_members/:id', to: 'crew_members#show', as: 'crew_member'
  get '/movies/:id/crew_members', to: 'crew_members#movie_index', as: 'movie_crew_members'
  
  post 'crew_members', to: 'crew_members#create', as: 'create_crew_members'


  ### Roles Routes ###
  get 'crew_members/:id/roles/new', to: 'roles#new', as: 'new_role'
  
  post 'roles/new', to: 'roles#create', as: 'roles'
  
  ###Directors Routes###
  
  get '/directors/edit', to: 'directors#edit', as: 'edit_director'
  get '/directors/:id', to: 'directors#show', as: 'director'
  get '/director/:id/friends', to: 'directors#friends', as: 'director_friends'
  get '/director/:id/friends/pending', to: 'directors#pending_friends', as: 'pending_friends'
  
  post '/directors', to: 'directors#create', as: 'directors'
  patch '/directors/:id', to: 'directors#update'
  delete '/directors/:id', to: 'directors#destroy'

  ###Projects Routes###

  get '/directors/:id/projects', to: 'projects#index', as: 'director_projects'
  get '/movies/:id/projects/new', to: 'projects#new', as: 'new_project'
  get '/projects/:id', to: 'projects#show', as: 'project'
  get '/movies/:id/projects', to: 'projects#movie_index', as: 'movie_projects'

  post '/projects', to: 'projects#create', as: 'projects'
  patch '/projects', to: 'projects#update'

  ###Movies###
  get '/movies', to: 'movies#index', as: 'movies'
  get '/directors/:id/movies', to: 'movies#director_index', as: 'director_movies'
  get '/movies/new', to: 'movies#new', as: 'new_movie'
  get '/movie/:id', to: 'movies#show', as: 'movie'

  post '/movies', to: 'movies#create'
  
  ###Project Crew Members###
  get '/projects/:id/crew_members/new', to: 'project_crew_members#new', as: 'new_project_crew_member'

  post '/projects/:id/crew_members', to: 'project_crew_members#create', as: 'project_crew_members'

  ###Friends###
  post '/friends', to: 'friends#create', as: 'friends'
  patch '/friends', to: 'friends#update'

  ###Posts###

  get '/directors/:id/posts', to: 'posts#director_index', as: 'director_posts'
  get '/posts/new', to: 'posts#new', as: 'new_post'
  get '/posts/:id', to: 'posts#show', as: 'post'

  post '/posts', to: 'posts#create', as: 'posts'


end

cinemake/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
   
    def user 
        if session[:user]
            user = Director.find(session[:user]["id"])
        end
    end


    def valid? 
       redirect_to login_path unless user  
    end
    
   
    before_action :valid?, except: [:welcome]

    def welcome
        if session[:user]
            redirect_to director_path(user)
        end
    end

    def search
        @search = params["search"]
        if params["category"]
            @category = params["category"]
        end
    end
end

cinemake/app/helpers/application_helper.rb
module ApplicationHelper
end

cinemake/app/views/application/search.html.erb
<br><br>
<div class="post">
<%= form_with url: search_path, local: true, method: 'get' do |f| %> 
    <%= f.label "Search: " %>
    <%= f.text_field :search, value: @search%>
    <%= f.select :category, options_for_select(["Movies", "Directors", "Actors", "Writers"]), :selected => @category %>
    <%= f.submit "Filter" %>
<% end %>
<hr class="hr3">
<% if @search == "" %>
<% else %>
<h3>Search Results:</h3>
<%if @category %>
    <h3>"<%=@search%>" in <%=@category%></h3><br><br>
    <hr class="hr">
    <%if @category == "Movies"%>
        <%if Movie.downcase_names.any?{|name| name.include?(@search.downcase)}%>
            <% Movie.all.select{|movie|movie.name.downcase.include?(@search.downcase)}.each do |movie| %>
                <div><h3><%= link_to "#{movie.name} (#{movie.release_year})", movie_path(movie) %></h3>
                <p><%= "Directed by: #{movie.director_names.join(", ")}"%></p>
                <p><%= movie.short_synopsis %></p></div><br>
            <% end %>
        <% else %>
            No Results Found
        <% end %>

    <%elsif @category == "Directors"%>
        <% if Director.names.any?{|name| name.downcase.include?(@search.downcase)} %>
            <div class="person_search"><% Director.all.select{|director|director.name.downcase.include?(@search.downcase)}.each do |director| %>
                <div class="card" style="width: 18rem;">
                        <img src="<%=director.image%>" class="card-img-top" alt="...">
                        <div class="card-body">
                        <h5 class="card-title"><%= link_to "#{director.name}", director_path(director) %></h5>
                        <% if director.movies.empty? %>
                            <p class="card-text">Ready to Start Making Movies</p>
                        <% else %>
                            <% r_movie = director.movies.sample %>
                            <p class="card-text"><%= "Known for: #{r_movie.name} (#{r_movie.release_year})"%></p>
                        <% end %>
                        </div>
                </div>
            <% end %></div>
        <% else %>
            No Results Found
        <% end %>

    <%elsif @category == "Actors"%>
    <% if CrewMember.actor_names.any?{|name| name.downcase.include?(@search.downcase)} %>
    <div class="person_search"><% CrewMember.actors.select{|actor|actor.name.downcase.include?(@search.downcase)}.each do |actor| %>
        <div class="card" style="width: 18rem;">
                <% if actor.image == ""%>
                    <img src="https://www.durst-group.com/media/news/koenigbauer2019/30022-006-w800.jpg" class="card-img-top" alt="..."">
                <% else %>
                    <img src="https://image.tmdb.org/t/p/original/<%=actor.image%>" class="card-img-top" alt="..."">
                <% end %>
                <div class="card-body">
                <h5 class="card-title"><%= link_to "#{actor.name}", crew_member_path(actor) %></h5>
                <% if actor.bio %>
                    <p class="card-text"><%=actor.short_bio%></p>
                <% else %>
                    <p class="card-text">Professional Actor</p>
                <% end %>
                </div>
            </div>
            <% end %></div>
        <% else %>
            No Results Found
        <% end %>

    <%elsif @category == "Writers"%>
    <% if CrewMember.writer_names.any?{|name| name.downcase.include?(@search.downcase)} %>
    <div class="person_search"><% CrewMember.writers.select{|writer|writer.name.downcase.include?(@search.downcase)}.each do |writer| %>
        <div class="card" style="width: 18rem;">
                <% if writer.image == ""%>
                    <img src="https://www.durst-group.com/media/news/koenigbauer2019/30022-006-w800.jpg" class="card-img-top" alt="..."">
                 <% else %>
                     <img src="https://image.tmdb.org/t/p/original/<%=writer.image%>" class="card-img-top" alt="..."">
                 <% end %>
                <div class="card-body">
                <h5 class="card-title"><%= link_to "#{writer.name}", crew_member_path(writer) %></h5>
                <% if writer.bio %>
                    <p class="card-text"><%=writer.short_bio%></p>
                <% else %>
                    <p class="card-text">Professional Writer</p>
                <% end %>
                </div>
            </div>
            <% end %></div>
        <% else %>
            No Results Found
        <% end %>

    <%end%>



<%else%>
    <h3>"<%=@search%>"</h3>
    <hr class="hr">
    <%if Movie.downcase_names.any?{|name| name.include?(@search.downcase)} && @search != ""%>
        <h4>Movies:</h4><br>
        <% Movie.all.select{|movie|movie.name.downcase.include?(@search.downcase)}.each do |movie| %>
            <div><h3><%= link_to "#{movie.name} (#{movie.release_year})", movie_path(movie) %></h3>
            <p><%= "Directed by: #{movie.director_names.join(", ")}"%></p>
            <p><%= movie.short_synopsis %></p></div><br>
        <% end %>
        <hr class="hr">
    <%end%>
    
    <% if Director.names.any?{|name| name.downcase.include?(@search.downcase)} && @search != ""%>
        <h4>Directors:</h4><br>
        <div class="person_search"><% Director.all.select{|director|director.name.downcase.include?(@search.downcase)}.each do |director| %>
            <div class="card" style="width: 18rem;">
            <img src="<%=director.image%>" class="card-img-top" alt="...">
            <div class="card-body">
            <h5 class="card-title"><%= link_to "#{director.name}", director_path(director) %></h5>
            <% if director.movies.empty? %>
                <p class="card-text">Ready to Start Making Movies</p>
            <% else %>
                <% r_movie = director.movies.sample %>
                <p class="card-text"><%= "Known for: #{r_movie.name} (#{r_movie.release_year})"%></p>
            <% end %>
            </div>
            </div>
        <% end %></div><br><hr class="hr"><br>
    <% end %>
    

    <% if CrewMember.actor_names.any?{|name| name.downcase.include?(@search.downcase)} && @search != "" %>
        <h4>Actors:</h4><br>
        <div class="person_search"><% CrewMember.actors.select{|actor|actor.name.downcase.include?(@search.downcase)}.each do |actor| %>
            <div class="card" style="width: 18rem;">
                <% if actor.image == ""%>
                    <img src="https://www.durst-group.com/media/news/koenigbauer2019/30022-006-w800.jpg" class="card-img-top" alt="..."">
                <% else %>
                    <img src="https://image.tmdb.org/t/p/original/<%=actor.image%>" class="card-img-top" alt="..."">
                <% end %>
            <div class="card-body">
            <h5 class="card-title"><%= link_to "#{actor.name}", crew_member_path(actor) %></h5>
            <% if actor.bio.empty? %>
                <p class="card-text">Professional Actor</p>
            <% else %>
                <p class="card-text"><%=actor.short_bio%></p>
            <% end %>
            </div>
            </div>
        <% end %></div><br><hr class="hr"><br>
    <% end %>

    <% if CrewMember.writer_names.any?{|name| name.downcase.include?(@search.downcase)} && @search != "" %>
        <h4>Writers:</h4><br>
        <div class="person_search"><% CrewMember.writers.select{|writer|writer.name.downcase.include?(@search.downcase)}.each do |writer| %>
            <div class="card" style="width: 18rem;">
            <% if writer.image == ""%>
                <img src="https://www.durst-group.com/media/news/koenigbauer2019/30022-006-w800.jpg" class="card-img-top" alt="..."">
            <% else %>
                <img src="https://image.tmdb.org/t/p/original/<%=writer.image%>" class="card-img-top" alt="..."">
            <% end %>
            <div class="card-body">
            <h5 class="card-title"><%= link_to "#{writer.name}", crew_member_path(writer) %></h5>
            <% if writer.bio.empty? %>
                <p class="card-text">Professional Writer</p>
            <% else %>
                <p class="card-text"><%=writer.short_bio%></p>
            <% end %>
            </div>
            </div>
        <% end %></div><br><br>
    <% end %>
    <% if Movie.downcase_names.any?{|name| name.include?(@search.downcase)} == false && Director.names.any?{|name| name.downcase.include?(@search.downcase)} == false && CrewMember.actor_names.any?{|name| name.downcase.include?(@search.downcase)} == false && CrewMember.writer_names.any?{|name| name.downcase.include?(@search.downcase)} == false %>
            No Results Found
    <% end %>
<%end%></div>
<%end%>

cinemake/app/views/application/welcome.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <title>Cinemake</title>
        </head>


        <body id="welcome_page">
        <div id="welcome_logo" ><img id="big_logo" src="/cinemake.png"></div>
        <div id="welcome_buttons"><%= link_to "Login", login_path %>
          <div style="color:rgb(104, 102, 102)">|</div>
        <%= link_to "Sign Up", signup_path %></div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>