cinemake/config/routes.rb
Rails.application.routes.draw do

  ###Application Routes ###
  get '/', to: 'application#welcome', as: 'welcome'
  get '/search', to: 'application#search', as: 'search'
  
  ###Session Routes
  get '/login', to: 'sessions#new', as: 'login'

  get '/signup', to: 'directors#new', as: 'signup'

  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout', as: 'logout'

  #Actors Test
  get '/test', to: 'actors#test', as: 'test'
  ###Crew Members###

  get '/crew_members/search', to: 'crew_members#index', as: 'crew_members_search'
  get '/crew_members/:id', to: 'crew_members#show', as: 'crew_member'
  get '/movies/:id/crew_members', to: 'crew_members#movie_index', as: 'movie_crew_members'
  
  post 'crew_members', to: 'crew_members#create', as: 'create_crew_members'


  ### Roles Routes ###
  get 'crew_members/:id/roles/new', to: 'roles#new', as: 'new_role'
  
  post 'roles/new', to: 'roles#create', as: 'roles'
  
  ###Directors Routes###
  
  get '/directors/edit', to: 'directors#edit', as: 'edit_director'
  get '/directors/:id', to: 'directors#show', as: 'director'
  get '/director/:id/friends', to: 'directors#friends', as: 'director_friends'
  get '/director/:id/friends/pending', to: 'directors#pending_friends', as: 'pending_friends'
  
  post '/directors', to: 'directors#create', as: 'directors'
  patch '/directors/:id', to: 'directors#update'
  delete '/directors/:id', to: 'directors#destroy'

  ###Projects Routes###

  get '/directors/:id/projects', to: 'projects#index', as: 'director_projects'
  get '/movies/:id/projects/new', to: 'projects#new', as: 'new_project'
  get '/projects/:id', to: 'projects#show', as: 'project'
  get '/movies/:id/projects', to: 'projects#movie_index', as: 'movie_projects'

  post '/projects', to: 'projects#create', as: 'projects'
  patch '/projects', to: 'projects#update'

  ###Movies###
  get '/movies', to: 'movies#index', as: 'movies'
  get '/directors/:id/movies', to: 'movies#director_index', as: 'director_movies'
  get '/movies/new', to: 'movies#new', as: 'new_movie'
  get '/movie/:id', to: 'movies#show', as: 'movie'

  post '/movies', to: 'movies#create'
  
  ###Project Crew Members###
  get '/projects/:id/crew_members/new', to: 'project_crew_members#new', as: 'new_project_crew_member'

  post '/projects/:id/crew_members', to: 'project_crew_members#create', as: 'project_crew_members'

  ###Friends###
  post '/friends', to: 'friends#create', as: 'friends'
  patch '/friends', to: 'friends#update'

  ###Posts###

  get '/directors/:id/posts', to: 'posts#director_index', as: 'director_posts'
  get '/posts/new', to: 'posts#new', as: 'new_post'
  get '/posts/:id', to: 'posts#show', as: 'post'

  post '/posts', to: 'posts#create', as: 'posts'


end

cinemake/app/models/post.rb
class Post < ApplicationRecord
    belongs_to :director
    belongs_to :movie, optional: true

    
    def short_body
        if self.body.length > 250
            self.body[0..250] + "..."
        else
            self.body
        end
    end
end

cinemake/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def director_index
        @director = Director.find(params[:id])
    end

    def new
        @post = Post.new
    end
    
    def create
        @post = Post.new(post_params)
        if @post.valid?
            @post.save
            redirect_to post_path(@post)
        else 
            render :new
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    private
    def post_params
        params.require(:post).permit(:director_id, :movie_id, :title, :body)
    end
    
end

cinemake/app/helpers/posts_helper.rb
module PostsHelper
end

cinemake/app/views/posts/director_index.html.erb
<div class="post">
<h2><%="#{@director.name}'s Posts"%></h2>
<br><br>
    <% if @director.id == session["user"]["id"] %>
        <%= link_to "New Post", new_post_path%><br>
    <% end %>
    <hr class="hr">
    <% if @director.posts.any? %>
        <% @director.posts.each do |post| %>
            <div><h4><%= link_to "#{post.title}", post_path(post) %></h4>
            <p>Created at: <%= post.created_at.asctime[0..15] %>
                <%if post.movie_id%>
                    <%= " | #{post.movie.name}"%>
                <% end %> </p>
            <p><%=post.short_body%></p>
            <hr class="hr3"></div>
        <% end %>
    <% else %>
        <p>This director has no posts.
    <% end %>
</div>

cinemake/app/views/posts/new.html.erb
<br>
<h3 class="post-form">New Post</h3><br>
<% user = Director.find(session["user"]["id"]) %>
  <%= form_with model: @post, url: posts_path, local: true do |f| %>
    <h4 class="post-form">
    <%= f.hidden_field :director_id, value: user.id %>
    <%= f.label :movie_id, 'Movie (optional): ' %>
    <%= f.collection_select :movie_id, user.movies, :id, :name, include_blank: true %>
    <%= f.text_field :title, placeholder: "Post Title" %>
    <%= f.submit "Create Post" %><br>
    <%= f.text_area :body, placeholder: "Write text here...", cols: 100, rows: 30 %></h4>
  <% end %>
 

cinemake/app/views/posts/show.html.erb
<br><br>
<div class="post"><h3><%= @post.title %></h3>
</h4>
    <% if @post.movie_id %>
    <%= link_to "#{@post.movie.name}", movie_path(@post.movie) %>
    | By:
    <%= link_to "#{@post.director.name}", director_path(@post.director) %>
    <%= "| Created #{@post.created_at.asctime[0..15]}" %>
    <% else %>
        <%= "By: #{@post.director.name} | Created #{@post.created_at.asctime[0..15]}" %>
    <% end %>
</h4>
<br><hr class="hr">
    <p>
    <%= simple_format(@post.body) %>
    </p>
<p><%= link_to "More by #{@post.director.name}", director_posts_path(@post.director)%></p>
</div>
   